### 获取用户信息
GET http://localhost:8080/user/getUserInfo
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjYjU1NjUyYThiYmY1NGFlNjhjNjllOGM2MWFhY2M1OTQiLCJhY2NvdW50SWQiOiJqYjFjMWYyNWJjZGZhNGNiZmI5NDc2NWUzMmE1Y2M0YmIiLCJjb2RlIjpudWxsLCJjcmVhdGVkIjoxNTE1NDAxMjA1NzI1LCJuaWNrTmFtZSI6bnVsbCwicm9sZXMiOm51bGwsIm1vYmlsZSI6bnVsbCwiaWQiOiJjYjU1NjUyYThiYmY1NGFlNjhjNjllOGM2MWFhY2M1OTQiLCJhdmF0YXIiOiJjYjU1NjUyYThiYmY1NGFlNjhjNjllOGM2MWFhY2M1OTQiLCJleHAiOjE1NDY5MzcyMDUsInVzZXJJZCI6ImNiNTU2NTJhOGJiZjU0YWU2OGM2OWU4YzYxYWFjYzU5NCJ9.6uWdbWAJsK4ft7lOdl6ike78yHkJdR8GcUASQGmvrZd5YmJbFqeGDJwQnv8R6d-n1PT1qNZUgwu9UBZEiNaOpQ

###
