### 提现页面
GET http://192.168.2.250:7777/wallet/withdraw
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjOGFjMTYyYmYzYTI0NDBiY2E0ZTU5MzI2MjFmZmI1NjQiLCJhY2NvdW50SWQiOiJqZmQxNGM1OTNmYmY2NDk0MThlMWI3OWJiNWVjZjEzMzkiLCJjb2RlIjpudWxsLCJjcmVhdGVkIjoxNTE1Mzc3MTg0NDU2LCJuaWNrTmFtZSI6bnVsbCwicm9sZXMiOm51bGwsIm1vYmlsZSI6bnVsbCwiaWQiOiJjOGFjMTYyYmYzYTI0NDBiY2E0ZTU5MzI2MjFmZmI1NjQiLCJhdmF0YXIiOiJjOGFjMTYyYmYzYTI0NDBiY2E0ZTU5MzI2MjFmZmI1NjQiLCJleHAiOjE1NDY5MTMxODQsInVzZXJJZCI6ImM4YWMxNjJiZjNhMjQ0MGJjYTRlNTkzMjYyMWZmYjU2NCJ9.lTCGYdwNpuwCRPRJqyx_X1GI-LLMqy9z1z9DB3OWb1FvoOIiTiVc2nnsh0JdQuAgJmqgzF5Ii53CG8oJxWmIJg

###
GET http://192.168.2.250:7777/getAddressList
Authorization: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjOGFjMTYyYmYzYTI0NDBiY2E0ZTU5MzI2MjFmZmI1NjQiLCJhY2NvdW50SWQiOiJqZmQxNGM1OTNmYmY2NDk0MThlMWI3OWJiNWVjZjEzMzkiLCJjb2RlIjpudWxsLCJjcmVhdGVkIjoxNTE1Mzc3MTg0NDU2LCJuaWNrTmFtZSI6bnVsbCwicm9sZXMiOm51bGwsIm1vYmlsZSI6bnVsbCwiaWQiOiJjOGFjMTYyYmYzYTI0NDBiY2E0ZTU5MzI2MjFmZmI1NjQiLCJhdmF0YXIiOiJjOGFjMTYyYmYzYTI0NDBiY2E0ZTU5MzI2MjFmZmI1NjQiLCJleHAiOjE1NDY5MTMxODQsInVzZXJJZCI6ImM4YWMxNjJiZjNhMjQ0MGJjYTRlNTkzMjYyMWZmYjU2NCJ9.lTCGYdwNpuwCRPRJqyx_X1GI-LLMqy9z1z9DB3OWb1FvoOIiTiVc2nnsh0JdQuAgJmqgzF5Ii53CG8oJxWmIJg